const TYPE_CLIENT = {
  CREATE_CLIENT: 'CREATE_CLIENT',
  DELETE_CLIENT: 'DELETE_CLIENT',
  UPDATE_CLIENT: 'UPDATE_CLIENT',
  UPDATE_DEPARTMENTS: 'UPDATE_DEPARTMENTS',
  UPDATE_PROVINCES: 'UPDATE_PROVINCES',
  UPDATE_DISTRICTS: 'UPDATE_DISTRICTS',
  UPDATE_PROFESSIONS: 'UPDATE_PROFESSIONS',
  UPDATE_POSITIONS: 'UPDATE_POSITIONS',
  UPDATE_ITEMS: 'UPDATE_ITEMS',
  UPDATE_BANKING_ENTITIES: 'UPDATE_BANKING_ENTITIES',
  UPDATE_DOCUMENT_TYPES: 'UPDATE_DOCUMENT_TYPES'
};

export default TYPE_CLIENT;
