const TYPES_PRODUCT_DETAIL = {
  UPDATE_PRODUCTS: 'UPDATE LIST PRODUCTS',
  UPDATE_CATEGORIES: 'UPDATE LIST CATEGORIES',
  UPDATE_PRODUCT_DETAIL: 'UPDATE PRODUCT DETAIL',
  UPDATE_CLIENT: 'UPDATE CLIENT',
  UPDATE_CATEGORY: 'UPDATE CATEGORY'
};

export default TYPES_PRODUCT_DETAIL;
